### ISSUE TITLE
Generated Swagger UI does not show all possible HTTP response codes

### ISSUE THREAD

**Issue by rkwright3** [richtea/Swashbuckle.AspNetCore.HealthChecks#34]
Hello,

When I customize the HealthCheckOptions in the call to MapHealthChecks() in my health check to do the following:

```
        ResultStatusCodes = new Dictionary<HealthStatus, int>()
        {
            [HealthStatus.Healthy] = StatusCodes.Status200OK,
            [HealthStatus.Degraded] = StatusCodes.Status500InternalServerError,
            [HealthStatus.Unhealthy] = StatusCodes.Status503ServiceUnavailable,
        },

```

the resulting Swagger UI only shows 200 and 503 as a possible response. It seems to be missing the customized Degraded response of 500. Am I missing something?

**Comment by richtea** [comment]
Hi @rkwright3 thanks for checking out this library :)

Unfortunately, I couldn't figure out a way for the library to access the definitions that are configured in the `HealthCheckOptions` at the right point in the configuration lifecycle, so it's unable to automatically generate matching result status codes. If you want to modify the codes that are reported in the swagger doc, you'll need to configure them explicitly by adding a response definition within the `WithOpenApi` extension method during your configuration. It would look something like this:

```csharp
app.MapHealthChecks(
        "/healthz",
        new HealthCheckOptions
        {
            ResponseWriter = reportFormatter.WriteDetailedReport,
        })
    .WithOpenApi<HealthCheckReport>(
        metadata =>
        {
            metadata.OperationId = "GET_healthz";
            metadata.Summary = "Returns information about the health of the system";
            metadata.ResponseDefinitions.Add(
                new HealthCheckResponseDefinition
                {
                    StatusCode = StatusCodes.Status500InternalServerError,
                    ResponseType = typeof(HealthCheckReport),
                });
        });
```

The key addition is the call to `metadata.ResponseDefinitions.Add()`

Please let me know how you get on!

**Comment by richtea** [comment]
Thanks for letting me know. And I'm glad you find the library useful!
